/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { useLoader } from '@react-three/fiber'
import { Canvas, useFrame } from '@react-three/fiber'


export default function Model(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/ness.glb')
    const colorMap = useLoader(TextureLoader, 'ness.png')
  
    useFrame((state, delta) => (group.current.rotation.y += 0.01))
    return (
        <group ref={group} {...props} dispose={null}>
            <primitive object={nodes.Bone} />
            <primitive object={nodes.Bone_L} />
            <primitive object={nodes.Bone_R} />
            <skinnedMesh
                geometry={nodes.nus.geometry}
                material={materials.nus_body}
                skeleton={nodes.nus.skeleton}
            >

                <meshStandardMaterial map={colorMap} />

            </skinnedMesh>


        </group>
    )
}

useGLTF.preload('/ness.glb')
